# Generated by Django 4.2 on 2023-06-02 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_comment_auction_listing"),
    ]

    operations = [
        migrations.RemoveField(model_name="auction_listing", name="price",),
        migrations.AddField(
            model_name="auction_listing",
            name="starting_value",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="auction_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.auction_listing",
            ),
        ),
        migrations.AlterField(
            model_name="auction_listing",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="auctions.category",
            ),
        ),
    ]
