# Generated by Django 4.1 on 2023-10-15 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_alter_comment_id_alter_following_id_alter_like_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="following",
            name="user_follow",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="following",
            name="user_followed_by",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
