# Generated by Django 4.1 on 2023-10-18 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_rename_created_by_like_liked_by_comment_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="count",
            new_name="total_count",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="count",
            new_name="total_count",
        ),
    ]
