# Generated by Django 4.1 on 2023-10-25 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_rename_count_comment_total_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="total_count",
        ),
        migrations.RemoveField(
            model_name="like",
            name="total_count",
        ),
    ]
