# Generated by Django 5.0.2 on 2024-08-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_comment_id_alter_following_id_alter_like_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('posts', models.ManyToManyField(related_name='hashtags', to='network.posts')),
            ],
        ),
    ]
