# Generated by Django 5.0.2 on 2024-08-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_hashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
