version: '3.8'

services:
    db:
        image: postgres:14
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres

    web:
        build: .
        volumes:
            - .:/cs50\twitter\docker-compose.yml

        ports:
            - "8000:8000"
