version: '3.8'

services:
    database:
        image: postgres:14
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: twitter
        ports:
            - "5432:5432"

    web:
        build:
            context: .
        command: sh -c 'pwd && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/usr/src/twitter
        env_file:
            - .env

        ports:
            - "8000:8000"
